name: Build

on:
  workflow_call: # from release
    inputs:
      ref:
        type: 'string'
        default: ${{github.ref}}
  pull_request:
    branches:
      - "main"
  push:
    branches:  # branches that are not used for release-please
      - "**"
      - "!main"
      - "!release-please-action"
jobs:
  build:
    strategy:
      matrix:
        ruby-version: ['2.7' , '3.0', '3.1', '3.2']
        os: ['ubuntu-latest'] # mac-os when/if Macfuse can be deployed on CI images
        fuse_pkg: ['fuse','fuse3']

    runs-on: ${{ matrix.os }}
    env:
      TERM: color # Pretty spec output
      GIT_REF: ${{ inputs.ref || github.ref }}
      GIT_BASE_REF: ${{ github.base_ref || 'undefined' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_REF }}
      - name: Preinstall
        env:
          FUSE_PKG: ${{ matrix.fuse_pkg }}
        run: .github/scripts/pre_install_${{runner.os}}.sh
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake