# Tag and Release
name: Release

on:
  workflow_dispatch:  # run for pre-existing tag or against a branch
  push: # If semver tag applied manually - probably not required
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"   # semver tags
  workflow_call: # From release-please
    inputs:
      ref:
        type: 'string'
        default: ${{github.ref}}
    secrets:
      RUBYGEMS_API_KEY:
        required: true
jobs:
  call-build:  # Ultra safety
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{ inputs.ref || github.ref }}
  release:
    needs: call-build
    runs-on: ubuntu-latest
    env:
      GIT_REF: ${{ inputs.ref || github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_REF }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Setup Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          git config user.name "${GITHUB_USER_NAME}"
          git config user.email "<>"
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
          GITHUB_USER_NAME: "GitHub Action ${{github.workflow}}"
      - name: Release
        run: bundle exec rake release
